[package]
name = "moros"
description = "MOROS: Omniscient Rust Operating System"
version = "0.1.0"
authors = ["Vincent Ollivier <v@vinc.cc>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/vinc/moros"
readme = "README.md"

[dependencies]
bootloader = { version = "0.8.3", features = ["map_physical_memory"]}
linked_list_allocator = "0.6.4"
volatile = "0.2.6"
spin = "0.5.2"
x86_64 = "0.8.1"
pic8259_simple = "0.1.1"
pc-keyboard = { git = "https://github.com/thejpster/pc-keyboard" }
bit_field = "0.10.0"
raw-cpuid = "7.0.3"
uart_16550 = "0.2.1"
lazy_static = { version = "1.0", features = ["spin_no_std"] }
base64 = { version = "0.11", default-features = false }
pbkdf2 = { version = "0.3", default-features = false }
sha2 = { version = "0.8", default-features = false }
hmac = { version = "0.7", default-features = false }
