[package]
name = "moros"
version = "0.1.0"
authors = ["Vincent Ollivier <v@vinc.cc>"]
edition = "2018"

[dependencies]
bootloader = "0.8.0"
volatile = "0.2.6"
spin = "0.5.2"
x86_64 = "0.8.1"
uart_16550 = "0.2.0"
pic8259_simple = "0.1.1"
pc-keyboard = "0.5.0"
heapless = "0.5.1"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
