[package]
name = "moros"
description = "MOROS: Omniscient Rust Operating System"
version = "0.1.0"
authors = ["Vincent Ollivier <v@vinc.cc>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/vinc/moros"
readme = "README.md"

[dependencies]
bootloader = "0.8.0"
volatile = "0.2.6"
spin = "0.5.2"
x86_64 = "0.8.1"
pic8259_simple = "0.1.1"
pc-keyboard = { version = "0.5.0", git = "https://github.com/vinc/pc-keyboard", branch = "feature/add-dvorak-layout" }
heapless = "0.5.1"
lazy_static = { version = "1.0", features = ["spin_no_std"] }
